# Generated by Django 5.2.7 on 2025-10-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
